package by.htp.ts.controller.command;

public enum CommandName {
	
	AUTHORIZATION, REGISTRATION, LOCALIZATION, LOGOUT, CREATE_TEST, TEACHER_COMMAND, SAVE_QUESTION,
	
	
	GO_TO_AUTHORIZATION_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_ERROR_PAGE, GO_TO_INDEX_PAGE,
	GO_TO_TEACHER_PAGE

}
