package by.htp.ts.controller.command;

public enum CommandName {

	AUTHORIZATION, REGISTRATION, LOCALIZATION, LOGOUT, CREATE_TEST,  SAVE_QUESTION, APPOINTMENT_TEST,
	FIND_AVAILABLE_TEST, PASS_TEST, START_TEST, NEXT_QUESTION,

	GO_TO_ERROR_PAGE, GO_TO_INDEX_PAGE, GO_TO_TEACHER_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_AUTHORIZATION_PAGE,
	GO_TO_STUDENT_PAGE, GO_TO_CREATE_TEST_PAGE, GO_TO_CREATE_QUESTION_PAGE, GO_TO_APPOINTMENT_TEST_PAGE

}
